#ifndef GODOT_FLATBUFFERS_FLATBUFFERBUILDER_HPP
#define GODOT_FLATBUFFERS_FLATBUFFERBUILDER_HPP

#include "flatbuffers/flatbuffer_builder.h"
#include <godot_cpp/classes/object.hpp>
#include <godot_cpp/classes/ref.hpp>
#include <godot_cpp/variant/utility_functions.hpp>

#include "godot_cpp/variant/variant_internal.hpp"

namespace godot_flatbuffers {
class FlatBufferBuilder final : public godot::RefCounted {
  GDCLASS( FlatBufferBuilder, RefCounted ) // NOLINT(*-use-auto)

  std::unique_ptr< flatbuffers::FlatBufferBuilder > builder;

  using uoffset_t = flatbuffers::uoffset_t;
  using Offset    = flatbuffers::Offset< >;

protected:
  static FlatBufferBuilder *Create( int size ) {
    const auto fbb = memnew( FlatBufferBuilder( size ) );
    fbb->builder   = std::make_unique< flatbuffers::FlatBufferBuilder >( size );
    // TODO Use this 'flatbuffers::FlatBufferBuilderImpl(...)' to add a custom allocator so that we can create directly into a PackedByteArray
    //  This will make the need to copy the data after construction unnecessary
    return fbb;
  }

  static void _bind_methods();

public:
  explicit FlatBufferBuilder();

  explicit FlatBufferBuilder( int size );

  [[nodiscard]] uoffset_t StartTable() const { return builder->StartTable(); }
  [[nodiscard]] uoffset_t EndTable( const uoffset_t start ) const { return builder->EndTable( start ); }

  void Finish( uint32_t root ) const;

  [[nodiscard]] godot::PackedByteArray GetPackedByteArray() const;

  [[nodiscard]] int64_t GetSize() const { return builder->GetSize(); }

  void Clear() const { builder->Clear(); }

  void Reset() const { builder->Reset(); }

  //MARK: Create
  // │  ___              _          [br]
  // │ / __|_ _ ___ __ _| |_ ___    [br]
  // │| (__| '_/ -_) _` |  _/ -_)   [br]
  // │ \___|_| \___\__,_|\__\___|   [br]
  // ╰───────────────────────────── [br]
  // Create is used when the data is offset from the table or struct or vector.

  // Pack a godot type to the table or struct and return its offset.
  // structs : Vector2, Vector2i, Rect2, Rect2i, Vector3, Vector3i, Transform2D,
  //           Vector4, Vector4i, Plane, Quaternion, AABB, Basis, Transform3D,
  //           Projection, Color
  // strings : String, StringName, NodePath
  // vectors : PackedByteArray, PackedInt32Array, PackedInt64Array,
  //           PackedFloat32Array, PackedFloat64Array, PackedVector2Array,
  //           PackedVector3Array, PackedColorArray, PackedVector4Array
  [[nodiscard]] uoffset_t CreateVariant(const godot::Variant &value, godot::Variant::Type variant_type ) const;


  // is a special case when handling offsets.
  [[nodiscard]] uoffset_t CreateVectorOfOffset( const godot::PackedInt32Array &array ) const;


  // template for creating vectors of scalars.
  template< typename T >
  [[nodiscard]] uoffset_t CreateVectorOfScalar( const godot::Array &v ) {
    builder->StartVector< T >( v.size() );
    for( auto i = v.size(); i > 0; ) {
      builder->PushElement( static_cast< T >(v[ --i ]) );
    }
    return builder->EndVector( v.size() );
  }


  // template for creating vectors of godot structs.
  template<typename packed_type>
  [[nodiscard]] uoffset_t CreateVectorOfStructs( const packed_type &packed ) const {
    return builder->CreateVectorOfStructs(packed.ptr(), packed.size() ).o;
  }

  // Custom structs are assumed to be the ones generated by the flatc compiler.
  [[nodiscard]] uoffset_t CreateVectorOfCustomStructs(const godot::Array &value, const size_t elem_size) const;


  // Custom Class to Table Creators
  [[nodiscard]] uoffset_t CreateVectorOfTable( const godot::Array &array, const godot::Callable &creator_func ) const;


  // Using the Callable provided, encode the value and type of an union member.
  // Returns offsets to the value and type vectors created.
  [[nodiscard]] godot::PackedInt32Array
  CreateVectorOfUnion( const godot::Array &array, const godot::Callable &creator_func ) const;


  //MARK: Add
  // │   _      _    _    [br]
  // │  /_\  __| |__| |   [br]
  // │ / _ \/ _` / _` |   [br]
  // │/_/ \_\__,_\__,_|   [br]
  // ╰─────────────────── [br]
  // Add is used when the data is inline with the table or struct

  // Add Offsets, offset is an unsigned 32 bit value.
  void AddOffset(const uint16_t voffset, const uint64_t value ) const { builder->AddOffset( voffset, Offset( value ) ); }


  // Add Arrays of arbitrary bytes treated as a single object for alignment purposes.
  void AddBytes( uint16_t voffset, const godot::PackedByteArray &bytes ) const;


  // template used to transform godot based scalars like int, and float, to any of the c++ types.
  // Scalars: bool, int64_t, int32_t, int16_t, int8_t, uint64_t, uint32_t, uint16_t, uint8_t, double, float
  template< typename in, typename out, bool with_default = false >
  std::enable_if_t< !with_default, void > AddScalar( uint16_t voffset, in value ) {
    builder->AddElement< out >( voffset, value );
  }


  // Same as AddScalar but with a default value
  template< typename in, typename out, bool with_default = false >
  std::enable_if_t< with_default, void > AddScalar( uint16_t voffset, in value, in def ) {
    builder->AddElement< out >( voffset, value, def );
  }


  // Add a godot type to the table or struct using voffset, optionally specify
  // which type is expected.
  // scalars : bool, int, float
  // structs : Vector2, Vector2i, Rect2, Rect2i, Vector3, Vector3i, Transform2D,
  //           Vector4, Vector4i, Plane, Quaternion, AABB, Basis, Transform3D,
  //           Projection, Color
  void AddGodotVariant(uint16_t voffset, const godot::Variant &value, godot::Variant::Type variant_type) const;

};

}  // namespace godot_flatbuffers
#endif //GODOT_FLATBUFFERS_FLATBUFFERBUILDER_HPP
